# Generated by Django 5.2.8 on 2025-11-25 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EXTRA',
            fields=[
                ('idExtra', models.AutoField(primary_key=True, serialize=False)),
                ('nombreExtra', models.CharField(max_length=50, unique=True)),
                ('tipoExtra', models.CharField(choices=[('DECORACION', 'cobertura'), ('SABOR', 'sabor'), ('RELLENO', 'relleno'), ('TAMANO', 'tamano')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTO',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField(default=0)),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('PASTEL', 'pastel'), ('TARTA', 'tarta'), ('POSTRE', 'postre'), ('PAN', 'pan')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PROMOCION',
            fields=[
                ('idPromocion', models.AutoField(primary_key=True, serialize=False)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vigencia', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='INACTIVA', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='USUARIO',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('nombreU', models.CharField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidoP', models.CharField(max_length=60)),
                ('apellidoM', models.CharField(blank=True, max_length=60, null=True)),
                ('direccionEntrega', models.CharField(blank=True, default='Sin dirección', max_length=35, null=True)),
                ('fechaN', models.DateField()),
                ('celular', models.CharField(max_length=20)),
                ('puntosReco', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PAN',
            fields=[
                ('idPan', models.OneToOneField(limit_choices_to={'tipo': 'PAN'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pasteleria.producto')),
                ('nombrePan', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('descripcion', models.CharField(blank=True, default='Sin descripción', max_length=255, null=True)),
                ('imagen', models.CharField(blank=True, default='Sin imagen', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PASTEL',
            fields=[
                ('idPastel', models.OneToOneField(limit_choices_to={'tipo': 'PASTEL'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pasteleria.producto')),
                ('tipoPastel', models.CharField(choices=[('ESTABLECIDO', 'establecido'), ('PERSONALIZADO', 'personalizado')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='POSTRE',
            fields=[
                ('idPostre', models.OneToOneField(limit_choices_to={'tipo': 'POSTRE'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pasteleria.producto')),
                ('nombrePostre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, default='Sin descripción', max_length=255, null=True)),
                ('imagen', models.CharField(blank=True, default='Sin imagen', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TARTA',
            fields=[
                ('idTarta', models.OneToOneField(limit_choices_to={'tipo': 'TARTA'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pasteleria.producto')),
                ('nombreTarta', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, default='Sin descripción', max_length=255, null=True)),
                ('imagen', models.CharField(blank=True, default='Sin imagen', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DETALLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pasteleria.producto')),
            ],
        ),
        migrations.CreateModel(
            name='PEDIDO',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEntrega', models.DateField()),
                ('horaEntrega', models.TimeField()),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('calificacion', models.IntegerField(blank=True, default=None, null=True)),
                ('tipoEntrega', models.CharField(choices=[('PICKUP', 'pickup'), ('DOMICILIO', 'domicilio')], max_length=20)),
                ('formaPago', models.CharField(choices=[('MERCADOPAGO', 'mercadopago'), ('TARJETA', 'tarjeta')], max_length=20)),
                ('status', models.CharField(choices=[('RECIBIDO', 'Pedido Recibido'), ('ELABORANDO', 'En proceso de elaboración'), ('LISTO', 'Listo para entrega'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='RECIBIDO', max_length=20)),
                ('productos', models.ManyToManyField(related_name='pedidos', through='pasteleria.DETALLE', to='pasteleria.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pasteleria.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='detalle',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pasteleria.pedido'),
        ),
        migrations.AddField(
            model_name='producto',
            name='promocion',
            field=models.ManyToManyField(blank=True, related_name='producto', to='pasteleria.promocion'),
        ),
        migrations.CreateModel(
            name='PASTEL_ESTABLECIDO',
            fields=[
                ('idEstablecido', models.OneToOneField(limit_choices_to={'tipoPastel': 'ESTABLECIDO'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pasteleria.pastel')),
                ('nombrePastel', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, default='Sin descripción', max_length=255, null=True)),
                ('imagen', models.CharField(blank=True, default='Sin imagen', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PASTEL_PERSONALIZADO',
            fields=[
                ('idPersonalizado', models.OneToOneField(limit_choices_to={'tipoPastel': 'PERSONALIZADO'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pasteleria.pastel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='detalle',
            constraint=models.UniqueConstraint(fields=('pedido', 'producto'), name='unique_pedido_producto'),
        ),
        migrations.AlterUniqueTogether(
            name='detalle',
            unique_together={('pedido', 'producto')},
        ),
        migrations.AddField(
            model_name='pastel_personalizado',
            name='extras',
            field=models.ManyToManyField(related_name='pasteles_personalizados', to='pasteleria.extra'),
        ),
    ]
